#!/bin/bash
#
# Copyright 2016-2017  Martin Scharm
#
# This file is part of bf-docker-tools.
# <https://github.com/binfalse/docker-tools>
# <https://binfalse.de/2016/12/03/handy-docker-tools/>
#
# bf-docker-tools is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# bf-docker-tools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bf-docker-tools. If not, see <http://www.gnu.org/licenses/>.

function help ()
{
    echo "USAGE: $0 [-c CID] [-h]"
    echo "  -c CID  show only the ip of container with id CID"
    echo "  -h      show this help"
}

CID=""


while getopts ":c:h" opt
do
    case $opt in
        c)
            CID="$OPTARG"
            ;;
        h)
            help
            exit 0
            ;;
        \?)
            help
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

if [ -n "$CID" ]
then
    docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}  {{.Name}}  '$CID $CID
else
    # get all ips for docker containers
    for i in $(docker ps | awk '{print $1}' | \grep -v CONTAINER)
    do
        docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}  {{.Name}}  '$i $i
    done | column -t
fi
