#!/bin/bash
#
# Copyright 2016-2021  Martin Scharm
#
# This file is part of bf-docker-tools.
# <https://github.com/binfalse/docker-tools>
# <https://binfalse.de/2016/12/03/handy-docker-tools/>
#
# bf-docker-tools is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# bf-docker-tools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bf-docker-tools. If not, see <http://www.gnu.org/licenses/>.

if [ -z "$1" ]
then
    echo "Please provide a container name/id that will be killed and removed"
    echo ""
    echo "Pass -f and this script will kill all running containers."
    exit 1
fi

if [ "$1" = "-f" ]
then
    # kill all running containers
    for i in $(docker ps | \grep Up | awk '{print $1}')
    do
        docker kill "$i"
    done
else
    # kill and remove a single container
    docker kill "$1" && docker rm "$1"
fi





