#!/bin/bash
#
# Copyright 2016-2017  Martin Scharm
#
# This file is part of bf-docker-tools.
# <https://github.com/binfalse/docker-tools>
# <https://binfalse.de/2016/12/03/handy-docker-tools/>
#
# bf-docker-tools is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# bf-docker-tools is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# bf-docker-tools. If not, see <http://www.gnu.org/licenses/>.

MODE="n"
#RESTART="n"

function help ()
{
    echo "USAGE: $0 [-v] [-s] [-h]"
    echo "  -v  verbose mode, also print images that have not been updates"
    echo "  -s  silent mode, do not print errors, just print updated images"
# that would be a cool feature, but not sure how to implement it, yet...
#    echo "  -r  restart containers that are based on images that were updated"
    echo "  -h  show this help"
}


while getopts ":vsh" opt
do
    case $opt in
        v)
            MODE="v"
            ;;
#        r)
#            RESTART="y"
#            ;;
        s)
            MODE="s"
            ;;
        h)
            help
            exit 0
            ;;
        \?)
            help
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done



for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | \grep -v '<none>')
do
    out=$(docker pull $i 2>&1 | \grep '^Status')
    if [ "$?" -ne 0 ]
    then
        [ "$MODE" == "s" ] || echo "error pulling $i"
    else
        if [[ "$out" =~ "Downloaded newer image" ]]
        then
            echo "$i was updated"
        elif [[ "$out" =~ "Image is up to date" ]]
        then
            [ "$MODE" == "v" ] && echo "$i is up-to-date"
        else
            echo $i -- $out
        fi
    fi
done
